Repository awslabs/aws-deployment-framework, pull requests merged in 2021-11, with the labels that each got.

#381 F/fix partition python
  resources/OrganizationAccountAccessRole.yaml
  samples/sample-ec2-with-codedeploy/template.yml
  samples/sample-ecr-repository/template.yml
  samples/sample-expunge-vpc/template.yml
  samples/sample-iam/template.yml
  samples/sample-service-catalog-product/productX/template.yml
  src/lambda_codebase/account_bootstrap.py
  src/lambda_codebase/cross_region_bucket/main.py
  src/lambda_codebase/determine_event.py
  src/lambda_codebase/generic_account_config.py
  src/lambda_codebase/initial_commit/adfconfig.yml.j2
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/enable_cross_account_access.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/regional.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/example-global-iam.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/organization_policy.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/provisioner/main.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_events.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_notifications.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/retrieve_organization_accounts.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/iam.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/partition.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/rule.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/stepfunctions.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_partition.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/repo.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/templates/events.yml
  src/lambda_codebase/moved_to_root.py
  src/lambda_codebase/organization/main.py
  src/lambda_codebase/organization_unit/main.py
  src/lambda_codebase/wait_until_complete.py
  src/template.yml
Labels: enhancement

#393 Bootstrap Repository Pipeline High Level Overview
  docs/images/TechnicalGuide-BootstrapRepo.png
  docs/technical-guide.md
Labels: docs

#401 Fix: Deployment Account Step Function Time outs
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/enable_cross_account_access.py
Labels: bug

#349 Adding support for CodeBuild to pull from docker hub
  docs/providers-guide.md
  docs/user-guide.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
Labels: enhancement

#343 Improvements to the SAR app template
  src/template.yml
Labels: enhancement

#367 Adding in the ability to use ChatBot configurations
  docs/admin-guide.md
  docs/user-guide.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_chatbot.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_notifications.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/adf_default_pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
Labels: enhancement

#403 Improved error message with accounts yml read failures
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/provisioner/src/configparser.py
Labels: enhancement

#389 adding in ability to define CodeCommit artifact format
  docs/providers-guide.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
Labels: enhancement

#370 Feature: added ability to override the default branch
  docs/admin-guide.md
  src/lambda_codebase/initial_commit/adfconfig.yml.j2
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py
  src/lambda_codebase/initial_commit/bootstrap_repository/example-adfconfig.yml
Labels: enhancement

#358 Feature: Wave Config for Targets
  docs/user-guide.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/adf_default_pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_default_pipeline_type.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/target.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_target.py
Labels: enhancement
