Repository awslabs/aws-deployment-framework, pull requests merged in 2022-01, with the labels that each got.

#423 Updating get account region function to use opted-in regions too
  src/lambda_codebase/account_processing/get_account_regions.py
Labels: enhancement

#418 Update docs to state the default branch used as the source
  docs/admin-guide.md
  docs/providers-guide.md
Labels: docs

#416 Change example email domains and account ids
  CONTRIBUTING.md
  docs/admin-guide.md
  docs/user-guide.md
  samples/sample-service-catalog-product/template.yml
  src/lambda_codebase/account/tests/test_main.py
  src/lambda_codebase/account_processing/tests/test_account_alias.py
  src/lambda_codebase/account_processing/tests/test_account_creation.py
  src/lambda_codebase/account_processing/tests/test_account_file_processing.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-accounts/readme.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/pipelines_repository/example-deployment_map.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/adf_codepipeline_test_constants.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codebuild_determine_build_image.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/sts.sh
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/stubs/stub_event.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/stubs/stub_kms.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_iam.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_organizations.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_deployment_map.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_target.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_deployment_map.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_target.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/stubs/stub_adfconfig.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/test_config.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/test_main.py
  src/lambda_codebase/initial_commit/bootstrap_repository/example-adfconfig.yml
  src/template.yml
Labels: enhancement, docs

#417 Update to CDK v1.137, pylint v2.12, and others to latest available
  requirements.txt
  src/lambda_codebase/account/main.py
  src/lambda_codebase/account_bootstrap.py
  src/lambda_codebase/event.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/enable_cross_account_access.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/slack.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/update_pipelines.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/config.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/organization_policy.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/provisioner/src/configparser.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_cloudformation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codecommit.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_events.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_github.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/adf_default_pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/clean_pipelines.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/execute_pipeline_stacks.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_stacks.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/deployment_map.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_params.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/retrieve_organization_accounts.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/parameter_store.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/rule.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/s3.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/stepfunctions.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_s3.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/repo.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/target.py
  src/lambda_codebase/initial_commit/initial_commit.py
  src/lambda_codebase/initial_commit/requirements.txt
  src/lambda_codebase/wait_until_complete.py
Labels: enhancement

#415 Upgrade to Python 3.9
  .travis.yml
  docs/user-guide.md
  samples/sample-cdk-app/buildspec.yml
  samples/sample-ec2-with-codedeploy/buildspec.yml
  samples/sample-ecr-repository/buildspec.yml
  samples/sample-ecs-cluster/buildspec.yml
  samples/sample-expunge-vpc/buildspec.yml
  samples/sample-expunge-vpc/template.yml
  samples/sample-fargate-node-app/buildspec.yml
  samples/sample-iam/buildspec.yml
  samples/sample-mono-repo/apps/alpha/buildspec.yml
  samples/sample-mono-repo/apps/beta/buildspec.yml
  samples/sample-serverless-app/buildspec.yml
  samples/sample-serverless-app/template.yml
  samples/sample-service-catalog-product/buildspec.yml
  samples/sample-terraform/my_test_spec.yml
  samples/sample-vpc/buildspec.yml
  src/account_processing.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/pipelines_repository/example-deployment_map.yml
  src/template.yml
  tox.ini
Labels: enhancement
