Repository awslabs/aws-deployment-framework, pull requests merged in 2022-08, with the labels that each got.

#412 specify acl for S3 objects
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/s3.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_s3.py
Labels: enhancement

#486 Update to CDK v1.168, pylint v2.13, and others to latest available
  requirements.txt
  src/lambda_codebase/account_processing/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt
  src/lambda_codebase/initial_commit/requirements.txt
  src/template.yml
Labels: dependencies

#489 Fix incorrect CodeBuild build/deploy references in params
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
Labels: bug

#498 Lock MarkupSafe to v2.0.1, as v2.1 breaks with jinja2<3.0.0
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/requirements.txt
  src/lambda_codebase/initial_commit/requirements.txt
Labels: bug

#501 Fix use of separate container image per target
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codebuild_determine_build_image.py
Labels: bug

#424 Refactor: Separate Pipeline Management into Serverless Application
  docs/images/TechnicalGuide-AccountManagementStateMachine.drawio.png
  docs/images/TechnicalGuide-BootstrapRepo.drawio.png
  docs/images/TechnicalGuide-BootstrapRepo.png
  docs/technical-guide.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/create_or_update_rule.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/create_repository.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/generate_pipeline_inputs.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/identify_out_of_date_pipelines.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/process_deployment_map.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/requirements.txt
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/store_pipeline_definition.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/templates/codecommit.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/templates/events.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/execute_pipeline_stacks.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudwatch.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/deployment_map.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/repo.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/schema_validation.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/target.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/stubs/stub_deployment_map.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/stubs/stub_target.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_deployment_map.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_pipeline.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_target.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_deployment_map.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_deployment_map.py
  src/template.yml
Labels: enhancement

#509 Add missing permission to assume Cross-Account-Org R/O role
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml
Labels: bug

#511 Fix permission to update termination protection on pipeline stacks
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
Labels: bug
