Repository awslabs/aws-deployment-framework, pull requests merged in 2023-08, with the labels that each got.

#636 feat: introduce-variable-org-stage
  docs/admin-guide.md
  src/lambda_codebase/initial_commit/adfconfig.yml.j2
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/test_main.py
Labels: enhancement

#650 Fix ChatBot channel ref + add notification management permissions
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_chatbot.py
Labels: bug

#649 Improve docs and add CodeStar Connection policy
  docs/admin-guide.md
  src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/example-global-iam.yml
Labels: enhancement, docs
